#!/bin/sh
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not handle the case statement correctly, you may need to use bash.
#
#   (2) Important: For projects using the Gradle Kotlin DSL,
#       this script is a shim that will only execute if you have a Kotlin DSL
#       build script in the root project folder.
#
##############################################################################

set -e

PRG="$0"

# Try to locate the Gradle distribution from wrapper properties
GRADLE_WRAPPER_PROPERTIES="${APP_HOME}gradle/wrapper/gradle-wrapper.properties"

while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

SAVED="`pwd`"
cd "`dirname \"$PRG\"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

# Check if wrapper jar exists, if not try to use installed gradle
if [ ! -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ] ; then
    # Use system gradle if available
    GRADLE_CMD="gradle"
else
    # Use wrapper
    GRADLE_CMD="$APP_HOME/gradlew"
fi

# Check if gradle is in PATH
if ! command -v gradle &> /dev/null ; then
    echo "Error: gradle is not installed and gradle-wrapper.jar not found"
    exit 1
fi

exec gradle "$@"
